name: ros_client
version: 0.0.1
description: My epic game!! (Client Side)
author: ewoudje
environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  ros_core:
    path: ../core
  ros_rest_api:
    path: ../rest-api

dev_dependencies:
  test: ^1.0.0