name: ros_server
description: My epic game!! (Server Side)
version: 0.0.1
author: ewoudje

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.2.0
  ros_core:
    path: ../core

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0